In [2]:
import torch as th


In [3]:
x = th.tensor([1,2,3,4,5])

In [4]:
x


tensor([1, 2, 3, 4, 5])

In [5]:
import syft as sy

/home/akshay/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
hook = sy.TorchHook(th)

In [7]:
th.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [8]:
bob = sy.VirtualWorker(hook,id="Bob")

In [9]:
x=x.send(bob)


In [10]:
bob._objects

{48901353870: tensor([1, 2, 3, 4, 5])}

In [11]:
x

(Wrapper)>[PointerTensor | me:94653228396 -> Bob:48901353870]

In [12]:
x.location

<VirtualWorker id:Bob #objects:1>

In [13]:
x.id_at_location

48901353870

In [14]:
x.id

94653228396

In [15]:
x.owner

<VirtualWorker id:me #objects:0>

In [16]:
hook.local_worker

<VirtualWorker id:me #objects:0>

In [17]:
x

(Wrapper)>[PointerTensor | me:94653228396 -> Bob:48901353870]

In [18]:
x=x.get()
x

tensor([1, 2, 3, 4, 5])

In [19]:
bob._objects

{}

In [20]:
alice = sy.VirtualWorker(hook,id="alice")

In [21]:
x=th.tensor([1,2,3,4,5])

In [22]:
x_ptr = x.send(bob,alice)

In [23]:
x_ptr.get()

[tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5])]

In [24]:
x=th.tensor([1,2,3,4,5]).send(bob,alice)

In [25]:
x.get(sum_results=True)

tensor([ 2,  4,  6,  8, 10])

In [26]:
input = th.tensor([[1.,1],[0,1],[1,0],[0,0]],requires_grad= True).send(bob)
target = th.tensor([[1.],[1],[0],[0]], requires_grad=True).send(bob)

In [27]:
weights = th.tensor([[0.],[0.]],requires_grad= True).send(bob)

In [28]:
for i in range(10):
    pred = input.mm(weights)
    loss = ((pred-target)**2).sum()
    loss.backward()
    weights.data.sub_(weights.grad*0.1)
    weights.grad*=0
    print(loss.get().data)

tensor(2.)
tensor(0.5600)
tensor(0.2432)
tensor(0.1372)
tensor(0.0849)
tensor(0.0538)
tensor(0.0344)
tensor(0.0220)
tensor(0.0141)
tensor(0.0090)
